# Список цілей для моніторингу (0–10 хостів, IPv4 або DNS)
hosts:
  - "8.8.8.8"
  - "1.1.1.1"
  - "google.com"
  - "cloudflare.com"
  - "github.com"
  - "ukr.net"
  - "kernel.org"
  - "debian.org"
  - "ubuntu.com"
